const WeatherUI = (() => {
  const temp = (value) => `${Math.round(value)}°`;
  const time = (value) => new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(new Date(value));
  const day = (value) => new Intl.DateTimeFormat(undefined, { weekday: 'short' }).format(new Date(value));
  function icon(code, isDay) { const info = WeatherCodes.get(code, isDay); const art = info.night ? '<path d="M18 15.5A7 7 0 1 1 8.5 6 5.5 5.5 0 0 0 18 15.5Z"/>' : ({clear:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',partly:'<path d="M7 16h10a4 4 0 0 0 0-8 5.5 5.5 0 0 0-10.5 2"/><circle cx="8" cy="8" r="3"/>',cloudy:'<path d="M5 17h13a4 4 0 0 0 .3-8A6 6 0 0 0 7 11"/>',fog:'<path d="M4 9h16M3 13h18M6 17h12"/>',drizzle:'<path d="M5 13h13a4 4 0 0 0 .3-8A6 6 0 0 0 7 7"/><path d="M8 17v1M12 17v1M16 17v1"/>',rain:'<path d="M5 13h13a4 4 0 0 0 .3-8A6 6 0 0 0 7 7"/><path d="M8 17l-1 3M13 17l-1 3M18 17l-1 3"/>',snow:'<path d="M5 13h13a4 4 0 0 0 .3-8A6 6 0 0 0 7 7"/><path d="M9 17v4M7.3 18l3.4 2M10.7 18l-3.4 2M15 17v4M13.3 18l3.4 2M16.7 18l-3.4 2"/>',storm:'<path d="M5 13h13a4 4 0 0 0 .3-8A6 6 0 0 0 7 7"/><path d="m12 15-2 4h3l-1 4 3-5h-3l2-3"/>'})[info.kind] || ''; return `<span class="weather-icon weather-${info.kind}" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${art}</svg></span>`; }
  function widget(weather) { const c = weather.data.current, d = weather.data.daily, info = WeatherCodes.get(c.weather_code, c.is_day); return `<a class="weather-widget" href="weather.html" aria-label="${t('Open detailed weather')}"><div>${icon(c.weather_code,c.is_day)}<div><p class="eyebrow">${t('Weather')}</p><h2>${temp(c.temperature_2m)} <small>${escapeHtml(info.label)}</small></h2><p>${escapeHtml(weather.location.name)} · ${t('Feels like')} ${temp(c.apparent_temperature)}</p></div></div><div class="weather-widget-meta"><strong>${t('High')} ${temp(d.temperature_2m_max[0])}</strong><span>${t('Low')} ${temp(d.temperature_2m_min[0])}</span><small>${t('Updated')} ${time(weather.updatedAt)}</small></div></a>`; }
  function skeleton() { return `<div class="weather-widget weather-widget-skeleton" aria-busy="true"><span></span><span></span><span></span></div>`; }
  function error(error) { return `<section class="weather-error"><strong>${t('Weather is unavailable')}</strong><p>${escapeHtml(error.message || t('Please check your connection and try again.'))}</p><button class="secondary-btn" type="button" data-weather-retry>${t('Retry')}</button><button class="text-btn" type="button" data-weather-search>${t('Choose a city')}</button></section>`; }
  function hero(weather) { const c=weather.data.current,d=weather.data.daily,info=WeatherCodes.get(c.weather_code,c.is_day); return `<section class="weather-hero weather-${info.kind}"><div><p class="eyebrow">${escapeHtml(weather.location.name)}${weather.location.country ? ` · ${escapeHtml(weather.location.country)}` : ''}</p><div class="weather-hero-temp">${temp(c.temperature_2m)} ${icon(c.weather_code,c.is_day)}</div><h2>${escapeHtml(info.label)}</h2><p>${new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date())} · ${t('Feels like')} ${temp(c.apparent_temperature)}</p></div><div class="weather-hero-highlow"><span>${t('High')} <b>${temp(d.temperature_2m_max[0])}</b></span><span>${t('Low')} <b>${temp(d.temperature_2m_min[0])}</b></span><span>${t('AQI')} <b>${t('Coming soon')}</b></span></div></section>`; }
  function hourly(weather) { const h=weather.data.hourly; return `<section class="weather-section"><div class="weather-section-head"><h2>${t('Next 24 hours')}</h2></div><div class="weather-hourly">${h.time.map((value,i)=>`<article><time>${i===0?t('Now'):time(value)}</time>${icon(h.weather_code[i],1)}<strong>${temp(h.temperature_2m[i])}</strong><small>${Math.round(h.wind_speed_10m[i])} km/h</small><small>${h.precipitation_probability[i]||0}%</small></article>`).join('')}</div></section>`; }
  function daily(weather) { const d=weather.data.daily; return `<section class="weather-section"><h2>${t('Five day forecast')}</h2><div class="weather-daily">${d.time.slice(0,5).map((value,i)=>{const info=WeatherCodes.get(d.weather_code[i]);return `<article tabindex="0"><strong>${i===0?t('Today'):day(value)}</strong>${icon(d.weather_code[i],1)}<span>${escapeHtml(info.label)}</span><b>${temp(d.temperature_2m_max[i])} / ${temp(d.temperature_2m_min[i])}</b></article>`}).join('')}</div></section>`; }
  function details(weather) { const c=weather.data.current,h=weather.data.hourly,d=weather.data.daily,i=0; const rows=[[t('UV Index'),d.uv_index_max[0]],[t('Humidity'),`${c.relative_humidity_2m}%`],[t('Pressure'),`${Math.round(c.pressure_msl)} hPa`],[t('Real Feel'),temp(c.apparent_temperature)],[t('Wind'),`${Math.round(c.wind_speed_10m)} km/h`],[t('Wind direction'),`${Math.round(c.wind_direction_10m)}°`],[t('Visibility'),`${Math.round((h.visibility[i]||0)/1000)} km`],[t('Cloud cover'),`${c.cloud_cover}%`],[t('Dew point'),temp(h.dew_point_2m[i])],[t('Sunrise'),time(d.sunrise[0])],[t('Sunset'),time(d.sunset[0])],[t('Rain probability'),`${d.precipitation_probability_max[0]||0}%`]]; return `<section class="weather-section"><h2>${t('Weather details')}</h2><div class="weather-details">${rows.map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join('')}</div></section>`; }
  function recommendations(items) { return items.length ? `<section class="weather-section weather-recommendations"><h2>${t('Recommendations')}</h2>${items.map(item=>`<p>${escapeHtml(item.text)}</p>`).join('')}</section>` : ''; }
  return { widget,skeleton,error,hero,hourly,daily,details,recommendations };
})();
window.WeatherUI = WeatherUI;
